env:
  browser: true
  es2022: true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
  - prettier
parserOptions:
  ecmaVersion: 12
plugins:
  - vue
  - '@typescript-eslint'
rules: {
  "vue/html-indent": [ "error", 2, {
    "attribute": 1,
    "baseIndent": 1,
    "closeBracket": 0,
    "alignAttributesVertically": true,
    "ignores": [ ]
  } ],
  "vue/max-attributes-per-line": [ "error", {
    "singleline": {
      "max": 1
    },
    "multiline": {
      "max": 1
    }
  } ],
  "vue/singleline-html-element-content-newline": [ "error", {
    "ignoreWhenNoAttributes": true,
    "ignoreWhenEmpty": true,
    "ignores": [ "div", "pre", "textarea" ]
  } ],
  "vue/multi-word-component-names": "off"
}
